### ISSUE TITLE
Crash when closing fullscreen mpv player.

### ISSUE THREAD

**Issue by pmts** [linuxmint/muffin#253]
cinnamon 3.06, muffin 3.0.5, mpv 0.18.1

1. open any video in mpv
2. press 'f' to go fullscreen
3. press 'q' to quit

At this point the window manager crashes and asks if I want to restart it. I can reproduce it 100% reliably on my system (Gentoo).

```
#0  meta_window_get_display (window=0x0) at core/window.c:11280
#1  0x00007fd4acb8809b in meta_window_actor_set_redirected (self=0x6158470, state=state@entry=1) at compositor/meta-window-actor.c:1316
#2  0x00007fd4acb7a9e2 in meta_pre_paint_func (data=0x15053a0) at compositor/compositor.c:1351
#3  0x00007fd4a98791ac in _clutter_run_repaint_functions (flags=flags@entry=CLUTTER_REPAINT_FLAGS_PRE_PAINT) at clutter-main.c:3449
#4  0x00007fd4a987aa37 in master_clock_update_stages (master_clock=0x7fd484003f80, stages=0x33c1a80) at clutter-master-clock-default.c:437
#5  clutter_clock_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at clutter-master-clock-default.c:567
#6  0x00007fd4a4c4d637 in g_main_dispatch (context=0xd7cc80) at /usr/src/debug/dev-libs/glib-2.48.1-r1/glib-2.48.1/glib/gmain.c:3154
#7  g_main_context_dispatch (context=context@entry=0xd7cc80) at /usr/src/debug/dev-libs/glib-2.48.1-r1/glib-2.48.1/glib/gmain.c:3769
#8  0x00007fd4a4c4d8c0 in g_main_context_iterate (context=0xd7cc80, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at /usr/src/debug/dev-libs/glib-2.48.1-r1/glib-2.48.1/glib/gmain.c:3840
#9  0x00007fd4a4c4dbe2 in g_main_loop_run (loop=0xd6f140) at /usr/src/debug/dev-libs/glib-2.48.1-r1/glib-2.48.1/glib/gmain.c:4034
#10 0x00007fd4acba5730 in meta_run () at core/main.c:542
#11 0x0000000000401b3d in main ()
```

**Comment by JosephMcc** [comment]
Please use the search when posting issues. This should already be fixed in git master. Relevant issue: https://github.com/linuxmint/muffin/issues/249
And fix: https://github.com/linuxmint/muffin/commit/fb54bc0f692f8b7adff1f89c74ab39c03fd024c1

**Comment by pmts** [comment]
Sorry. Searched for 'mpv', didn't find anything.
