### ISSUE TITLE
[BUG] Cinnamon randomly crashes

### ISSUE THREAD

**Issue by mxr576** [linuxmint/muffin#640]
```
 * Cinnamon version (cinnamon --version): 5.4.12
   - Please specify if you are using the daily builds PPA: NO
 * Distribution - Mint 21
 * Graphics hardware *and* driver used: No-additional driver, just what is comes with LM21/Ubuntu 22.04 for AMD Ryzen 7 PRO 4750U with Radeon Graphics
64 bit
 ```

### Issue

Cinnamon randomly crashes, mostly when Google Meets, Miro or VLC is running (if that helps).

[log2.txt](https://github.com/linuxmint/cinnamon/files/9493798/log2.txt)
[log1.txt](https://github.com/linuxmint/cinnamon/files/9493799/log1.txt)

### Configuration info, if applicable
-

**Comment by mxr576** [comment]
I fail to see how the removal of an application makes Cinnamon more stable... I am not going to try that, but good to know :D

**Comment by mtwebster** [comment]
Did this behavior just start with 5.4.12 (released yesterday)?

@hadi-f90 Your crash looks like it's not the same cause as the OP.

Can you both try:
- Create a new user account and try to reproduce the issue.
- Try to reproduce it with effects disabled (Cinnamon settings->Effects "Desktop and window effects")
- Provide the coredump info for these crashes (On Mint, run 'System Reports' and go to 'Crash Reports', then 'local files' - I only need the compressed file).

Thanks

**Comment by mxr576** [comment]
@mtwebster I have this issue since I updated to LM21 which was 2-3 weeks ago. I'll try to disable desktop effects, I do not really I have time for creating a new account, but I'll consider it.

**Comment by hadi-f90** [comment]
> Did this behavior just start with 5.4.12 (released yesterday)?
> 
> @hadi-f90 Your crash looks like it's not the same cause as the OP.
> 
> Can you both try:
> 
>     * Create a new user account and try to reproduce the issue.
> 
>     * Try to reproduce it with effects disabled (Cinnamon settings->Effects "Desktop and window effects")
> 
>     * Provide the coredump info for these crashes (On Mint, run 'System Reports' and go to 'Crash Reports', then 'local files' - I only need the compressed file).
> 
> 
> Thanks

Well, before I uninstall VLC, I tried diabling extensions and desktop effects one by one, since I had several spices with fuction and module incompatibilty warnings. However, even uninstalling them didn't resolved the issue.
As far as I remember, these setting were enabled when VLC was installed:
 "open with default action" was set for media files to VLC. 
 Thumbnail making facility for media files in VLC.
 I'll give it a try later in my free time. Hoping it to crash, yet again!

**Comment by judicandus** [comment]
Hello, 

I've been dealing with constant cinnamon crashes since installing Mint on my Surface Book 2 Laptop last week. 
**Crashes happen mainly when:** Changing Workspaces, using the files app, alt + tabbing between windows, usually it would crash right after logon as well.  

I thought at first it was being caused by hybrid Nvidia GPU + Intel so I experimented changing to Noveau and changing to several different Nvidia driver versions but nothing helped. Looking at the syslogs I found:```

Oct 25 04:17:10 SurfaceMint kernel: [ 1548.324495] cinnamon[5889]: segfault at 20 ip 00007f1242197e14 sp 00007ffc245cc8e0 error 4 in libmuffin-clutter-0.so.0.0.0[7f124217a000+a8000]
Oct 25 04:17:10 SurfaceMint kernel: [ 1548.324508] Code: 0f b6 90 20 03 00 00 f6 c2 e0 74 3b 83 ca e0 88 90 20 03 00 00 41 f6 47 18 02 74 07 80 88 23 03 00 00 10 48 8b b8 48 01 00 00 <48> 8b 47 20 f6 47 1c 01 75 13 0f b6 80 20 03 00 00 83 e0 e0 3c e0
Oct 25 04:17:10 SurfaceMint systemd[1]: Started Process Core Dump (PID 6346/UID 0).
```
Which brought me to this thread. 

Following mtwebster's advice I disabled Desktop and window effects in settings and the problem disappeared. I re-enabled Desktop and Windows Effects, and the problem hasn't presented itself again. I don't know if disabling and re-enabling this option resets anything but it fixed it for me. If I'm able to reproduce this problem again I'll post here. If there is any dump or log file I can contribute to help diagnose the exact cause please let me know.

**Comment by mxr576** [comment]
FTR, disabled desktop effects helped in my case.

**Comment by judicandus** [comment]
> FTR, disabled desktop effects helped in my case.

In my case it seemed to have worked, but it still has been crashing randomly for this past week when using high resource apps like thunderbird, firefox, or just when changing workspaces quickly. It crashes around 5-6 times per day.

**Comment by kremit** [comment]
I'm having similar issues, same library segfault, after upgrading to Fedora 37:

```
$ dnf list installed "*cinnamon*"
Installed Packages
cinnamon.x86_64                                                 5.6.8-2.fc37                          @updates
cinnamon-calendar-server.x86_64                                 5.6.8-2.fc37                          @updates
cinnamon-control-center.x86_64                                  5.6.1-1.fc37                          @updates
cinnamon-control-center-filesystem.x86_64                       5.6.1-1.fc37                          @updates
cinnamon-desktop.x86_64                                         5.6.1-1.fc37                          @updates
cinnamon-menus.x86_64                                           5.6.0-1.fc37                          @updates
cinnamon-screensaver.x86_64                                     5.6.3-1.fc37                          @updates
cinnamon-session.x86_64                                         5.6.0-1.fc37                          @updates
cinnamon-settings-daemon.x86_64                                 5.6.2-1.fc37                          @updates
cinnamon-themes.noarch                                          1:2.0.8-1.fc37                        @updates
cinnamon-translations.noarch                                    5.6.1-1.fc37                          @updates
imsettings-cinnamon.x86_64                                      1.8.3-8.fc37                          @updates
```

- Cinnamon version (cinnamon --version): 5.6.8
- Graphics: NVIDIA - akmod-nvidia.x86_64   3:530.41.03-1.fc37 

Coredump was 542MB (!) so I've added the core_backtrace here:
https://termbin.com/j6bn

It may have something to do with system tray icons coming and going - Slack, Spotify (Flatpak), VPN. I will try killing/upgrading some of those to see if it helps. May also be reflowing of the panel bar, which seems to jump around from time to time when the clock widget changes, but that seems to be a style issue with my particular theme/desktop font settings.

**Comment by kremit** [comment]
Some additional data points. I've ran cinnamon from the terminal (replacing running version with `cinnamon -d ':0' -r`) and recorded some potentially related errors that occurred around the time and then right at the time of crash:
https://termbin.com/0qdz

**Comment by kremit** [comment]
Seems those links have expired; I still have to run cinnamon in a loop in a background terminal. Two different errors within a few seconds/minutes of the segfaults:

Crash 1:

```
(cinnamon:742760): Gjs-WARNING **: 11:47:32.106: JS ERROR: Exception in callback for signal: status-icon-removed: TypeError: parent is null
_onTrayIconRemoved@/usr/share/cinnamon/applets/systray@cinnamon.org/applet.js:218:9
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
_onTrayIconRemoved@/usr/share/cinnamon/js/ui/statusIconDispatcher.js:64:14


(cinnamon:742760): Clutter-WARNING **: 11:47:32.135: Spurious clutter_actor_allocate called for actor 0x5608931227f0/CinnamonTrayIcon which isn't a descendent of the stage!


(cinnamon:742760): Clutter-CRITICAL **: 11:48:11.774: clutter_actor_is_visible: assertion 'CLUTTER_IS_ACTOR (self)' failed
Segmentation fault (core dumped)
```

Crash 2:

```
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x7600004
Segmentation fault (core dumped)
```

**Comment by Fantu** [comment]
to make possible to developers found and solves the cause of crash a backtrace (using gdb) with symbols (installing symbols packages of all components involved) is needed
depending on the distribution used there may be howtos and tools (debuginfod, coredumpctl etc...) to facilitate these operations

**Comment by kremit** [comment]
I was finally able to get a backtrace of the segfault by attaching to cinnamon via gdb in a screen session, with logging, so I could recover my desktop after the crash...

The segfault occurred as I was closing a Files (Nemo) window.

Short backtrace
```
#0  0x00007f5afe4cf2ad in clutter_actor_is_visible (self=0x5558949976e0) at ../clutter/clutter/clutter-actor.c:1962
#1  0x00007f5afdfaad45 in st_bin_allocate (self=0x555891492fc0 [StBin], box=0x555892155da0, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../src/st/st-bin.c:113
#2  0x00007f5afe4e005f in clutter_actor_allocate_internal (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, allocation=<optimized out>, self=0x555891492fc0 [StBin]) at ../clutter/clutter/clutter-actor.c:10315
#3  clutter_actor_set_animatable_property (actor=0x555891492fc0 [StBin], prop_id=<optimized out>, value=0x7fff1697d950, pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:15075
#4  0x00007f5afe4ea931 in _clutter_actor_create_transition (actor=0x555891492fc0 [StBin], pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:19560
#5  0x00007f5afe4dc5cf in clutter_actor_allocate (self=0x555891492fc0 [StBin], box=<optimized out>, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:10466
#6  0x00007f5afe4e5e90 in clutter_actor_allocate_align_fill (self=0x555891492fc0 [StBin], box=0x7fff1697dd40, x_align=<optimized out>, y_align=0.5, x_fill=1, y_fill=1, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:15803
#7  0x00007f5afe4f640c in allocate_box_child (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, child_box=0x7fff1697dd40, child=0x555891492fc0 [StBin], container=0x55587e9df8f0, self=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:774
#8  clutter_box_layout_allocate (layout=<optimized out>, container=<optimized out>, box=0x7fff1697de00, flags=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:1251
#9  0x00007f5afdfce66a in st_viewport_allocate (actor=0x55587e9df8f0 [StBoxLayout], box=0x555894762e00, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../src/st/st-viewport.c:268
#10 0x00007f5afe4e005f in clutter_actor_allocate_internal (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, allocation=<optimized out>, self=0x55587e9df8f0 [StBoxLayout]) at ../clutter/clutter/clutter-actor.c:10315
#11 clutter_actor_set_animatable_property (actor=0x55587e9df8f0 [StBoxLayout], prop_id=<optimized out>, value=0x7fff1697df30, pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:15075
#12 0x00007f5afe4ea931 in _clutter_actor_create_transition (actor=0x55587e9df8f0 [StBoxLayout], pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:19560
#13 0x00007f5afe4dc5cf in clutter_actor_allocate (self=0x55587e9df8f0 [StBoxLayout], box=<optimized out>, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:10466
#14 0x00007f5afe4e5e90 in clutter_actor_allocate_align_fill (self=0x55587e9df8f0 [StBoxLayout], box=0x7fff1697e300, x_align=<optimized out>, y_align=0.5, x_fill=1, y_fill=1, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:15803
#15 0x00007f5afe4f640c in allocate_box_child (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, child_box=0x7fff1697e300, child=0x55587e9df8f0 [StBoxLayout], container=0x55587e5666f0, self=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:774
#16 clutter_box_layout_allocate (layout=<optimized out>, container=<optimized out>, box=0x7fff1697e3c0, flags=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:1251
#17 0x00007f5afdfce66a in st_viewport_allocate (actor=0x55587e5666f0 [StBoxLayout], box=0x555884023aa0, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../src/st/st-viewport.c:268
#18 0x00007f5afe4e005f in clutter_actor_allocate_internal (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, allocation=<optimized out>, self=0x55587e5666f0 [StBoxLayout]) at ../clutter/clutter/clutter-actor.c:10315
#19 clutter_actor_set_animatable_property (actor=0x55587e5666f0 [StBoxLayout], prop_id=<optimized out>, value=0x7fff1697e4f0, pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:15075
#20 0x00007f5afe4ea931 in _clutter_actor_create_transition (actor=0x55587e5666f0 [StBoxLayout], pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:19560
#21 0x00007f5afe4dc5cf in clutter_actor_allocate (self=0x55587e5666f0 [StBoxLayout], box=<optimized out>, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:10466
#22 0x00007f5afe4e5e90 in clutter_actor_allocate_align_fill (self=0x55587e5666f0 [StBoxLayout], box=0x7fff1697e970, x_align=<optimized out>, y_align=0.5, x_fill=1, y_fill=1, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:15803
#23 0x00007f5afe4f640c in allocate_box_child (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, child_box=0x7fff1697e970, child=0x55587e5666f0 [StBoxLayout], container=0x55587cfc5c30, self=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:774
#24 clutter_box_layout_allocate (layout=<optimized out>, container=<optimized out>, box=0x7fff1697ea30, flags=<optimized out>) at ../clutter/clutter/clutter-box-layout.c:1251
#25 0x00007f5afdfce66a in st_viewport_allocate (actor=0x55587cfc5c30 [StBoxLayout], box=0x555888b0f000, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../src/st/st-viewport.c:268
#26 0x00007f5afe4e005f in clutter_actor_allocate_internal (flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED, allocation=<optimized out>, self=0x55587cfc5c30 [StBoxLayout]) at ../clutter/clutter/clutter-actor.c:10315
#27 clutter_actor_set_animatable_property (actor=0x55587cfc5c30 [StBoxLayout], prop_id=<optimized out>, value=0x7fff1697eb60, pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:15075
#28 0x00007f5afe4ea931 in _clutter_actor_create_transition (actor=0x55587cfc5c30 [StBoxLayout], pspec=0x55587c2042d0 [GParamBoxed]) at ../clutter/clutter/clutter-actor.c:19560
#29 0x00007f5afe4dc5cf in clutter_actor_allocate (self=0x55587cfc5c30 [StBoxLayout], box=<optimized out>, flags=CLUTTER_ABSOLUTE_ORIGIN_CHANGED) at ../clutter/clutter/clutter-actor.c:10466
#30 0x00007f5afce25a06 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#31 0x00007f5afce2249d in ffi_call_int (cif=cif@entry=0x55587d0fc848, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#32 0x00007f5afce25083 in ffi_call (cif=0x55587d0fc848, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at ../src/x86/ffi64.c:710
#33 0x00007f5afde944fd in Gjs::Function::invoke(JSContext*, JS::CallArgs const&, JS::Handle<JSObject*>, _GIArgument*) (this=0x55587d0fc830, context=0x55587c2bc620, args=..., this_obj=..., r_value=0x0) at ../gi/function.cpp:950
#34 0x00007f5afde94fc7 in Gjs::Function::call(JSContext*, unsigned int, JS::Value*) (context=0x55587c2bc620, js_argc=<optimized out>, vp=<optimized out>) at /usr/include/mozjs-78/js/RootingAPI.h:596
#35 0x0000217c1dd3f2d7 in  ()
#36 0x00003d3585814080 in  ()
#37 0x00007fff1697f218 in  ()
#38 0x00007fff1697f328 in  ()
#39 0x0000000000000000 in  ()
Detaching from program: /usr/bin/cinnamon, process 3966181
[Inferior 1 (process 3966181) detached]
```

Full bt with all threads is here:
[gdb.txt](https://github.com/linuxmint/muffin/files/13944069/gdb.txt)
